import type { TaskExecutionLog } from "./types";

// ============================================================================
// Mock data for development — remove when SSE is wired
// ============================================================================

export const MOCK_TASKS: TaskExecutionLog[] = [
  {
    task: {
      taskId: "TSK-A7x",
      objective: "Identify causal factors linking BRCA1 mutations to triple-negative breast cancer prognosis",
      requiredTools: ["literature_search"],
      outputSchemaName: "WorkerResult",
      status: "running",
      attemptCount: 1,
      maxAttempts: 3,
      createdAt: new Date(Date.now() - 12400).toISOString(),
    },
    attempts: [
      {
        attemptNumber: 1,
        promptSent: "Search for papers on BRCA1 and triple-negative breast cancer...",
        rawResponse: "",
        validationPassed: false,
        configUsed: { temperature: 0.7, top_p: 0.9, top_k: 40, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 12400).toISOString(),
        latencyMs: 12400,
        tokensUsed: 3420,
        ttftMs: 910,
        totalMs: 12400,
        tokensInput: 2100,
        tokensOutput: 1320,
        costUsd: 0.018,
      },
    ],
  },
  {
    task: {
      taskId: "TSK-B2m",
      objective: "Meta-analysis of CRISPR-Cas9 off-target rates across cell types",
      requiredTools: ["literature_search"],
      outputSchemaName: "WorkerResult",
      status: "fixing",
      attemptCount: 2,
      maxAttempts: 3,
      createdAt: new Date(Date.now() - 45000).toISOString(),
    },
    attempts: [
      {
        attemptNumber: 1,
        promptSent: "Search for meta-analyses on CRISPR off-target effects...",
        rawResponse: '{"summary": "CRISPR off-target rates vary...", "confidence": 1.5}',
        validationPassed: false,
        errorTrace: "ValidationError: confidence\n  Input should be less than or equal to 1.0\n    value=1.5",
        configUsed: { temperature: 0.7, top_p: 0.9, top_k: 40, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 45000).toISOString(),
        latencyMs: 14200,
        tokensUsed: 4100,
        ttftMs: 980,
        totalMs: 14200,
        tokensInput: 2500,
        tokensOutput: 1600,
        costUsd: 0.022,
      },
      {
        attemptNumber: 2,
        promptSent: "REVISED: Search for meta-analyses on CRISPR off-target effects. Your confidence score MUST be between 0.0 and 1.0 inclusive...",
        rawResponse: "",
        validationPassed: false,
        errorTrace: "EpistemicViolation: Worker cited reference IDs {7, 12} that were never returned by literature_search. Served IDs: {1, 2, 3, 4, 5, 6}",
        fixerDiagnostics: {
          failure_point: "Worker output confidence value 1.5 exceeds the allowed range [0.0, 1.0].",
          correction_strategy: "Inject explicit numeric constraint into prompt: 'confidence must be a float between 0.0 and 1.0'.",
        },
        rewrittenPrompt: "REVISED: ...confidence must be a float between 0.0 and 1.0...",
        configUsed: { temperature: 0.0, top_p: 0.1, top_k: 1, seed: 0xa3f2, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 30000).toISOString(),
        latencyMs: 8900,
        tokensUsed: 3800,
        ttftMs: 620,
        totalMs: 8900,
        tokensInput: 2200,
        tokensOutput: 1600,
        costUsd: 0.019,
      },
    ],
  },
  {
    task: {
      taskId: "TSK-C9z",
      objective: "Survey immunotherapy response predictors in non-small cell lung cancer",
      requiredTools: ["literature_search", "get_paper_detail"],
      outputSchemaName: "WorkerResult",
      status: "escalated",
      attemptCount: 3,
      maxAttempts: 3,
      createdAt: new Date(Date.now() - 120000).toISOString(),
    },
    attempts: [
      {
        attemptNumber: 1,
        promptSent: "Search for immunotherapy predictors in NSCLC...",
        rawResponse: '{"summary": "PD-L1 expression is the primary predictor...", "confidence": 1.5}',
        validationPassed: false,
        errorTrace: "ValidationError: confidence\n  Input should be less than or equal to 1.0\n    value=1.5",
        configUsed: { temperature: 0.7, top_p: 0.9, top_k: 40, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 120000).toISOString(),
        latencyMs: 14200,
        tokensUsed: 4100,
        ttftMs: 980,
        totalMs: 14200,
        tokensInput: 2500,
        tokensOutput: 1600,
        costUsd: 0.022,
      },
      {
        attemptNumber: 2,
        promptSent: "REVISED: confidence must be 0.0-1.0...",
        rawResponse: '{"summary": "TMB and PD-L1...", "confidence": 0.8, "cited_reference_ids": [7]}',
        validationPassed: false,
        errorTrace: "EpistemicViolation: Worker cited reference IDs {7} that were never returned by literature_search. Served IDs: {1, 2, 3, 4, 5, 6}",
        fixerDiagnostics: {
          failure_point: "Worker output confidence value 1.5 exceeds allowed range.",
          correction_strategy: "Inject explicit constraint into prompt.",
        },
        rewrittenPrompt: "REVISED v2...",
        configUsed: { temperature: 0.0, top_p: 0.1, top_k: 1, seed: 0xb7e1, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 90000).toISOString(),
        latencyMs: 8900,
        tokensUsed: 3800,
        ttftMs: 620,
        totalMs: 8900,
        tokensInput: 2200,
        tokensOutput: 1600,
        costUsd: 0.019,
      },
      {
        attemptNumber: 3,
        promptSent: "REVISED v3: Only cite reference IDs 1-6...",
        rawResponse: '{"summary": "...", "evidence": [{"strength": "high"}]}',
        validationPassed: false,
        errorTrace: "ValidationError: evidence[2].strength\n  Input should be 'strong', 'moderate', or 'weak'\n    value='high'",
        fixerDiagnostics: {
          failure_point: "Hallucinated reference ID 7 not in served set.",
          correction_strategy: "Enumerate valid IDs explicitly in prompt.",
        },
        rewrittenPrompt: "REVISED v3...",
        configUsed: { temperature: 0.0, top_p: 0.1, top_k: 1, seed: 0xb7e1, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 60000).toISOString(),
        latencyMs: 9200,
        tokensUsed: 3900,
        ttftMs: 640,
        totalMs: 9200,
        tokensInput: 2300,
        tokensOutput: 1600,
        costUsd: 0.020,
      },
    ],
    escalationPayload: {
      taskId: "TSK-C9z",
      workerObjective: "Survey immunotherapy response predictors in non-small cell lung cancer",
      errorType: "PydanticValidationError",
      errorMessage: "ValidationError: evidence[2].strength\n  Input should be 'strong', 'moderate', or 'weak'\n    value='high'",
      metrics: { ttft: 890, tps: 42.3, cost: 0.061 },
      attemptedReasoning: [
        "Searched for 'immunotherapy response predictors NSCLC'",
        "Found 12 papers, filtered to 8 peer-reviewed",
        "Extracted PD-L1, TMB, and MSI-H as primary predictors",
        "Attempted to structure evidence items with strength scores",
        "Used 'high' instead of 'strong' for evidence strength enum",
      ],
    },
  },
  {
    task: {
      taskId: "TSK-D4k",
      objective: "Compare structural equation modeling approaches for mediation analysis in epidemiology",
      requiredTools: ["literature_search"],
      outputSchemaName: "WorkerResult",
      status: "succeeded",
      attemptCount: 1,
      maxAttempts: 3,
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
    attempts: [
      {
        attemptNumber: 1,
        promptSent: "Search for SEM approaches in epidemiological mediation analysis...",
        rawResponse: '{"summary": "Baron-Kenny and counterfactual approaches dominate...", "confidence": 0.82}',
        validationPassed: true,
        configUsed: { temperature: 0.7, top_p: 0.9, top_k: 40, response_format: { type: "json_object" } },
        timestamp: new Date(Date.now() - 290000).toISOString(),
        latencyMs: 11300,
        tokensUsed: 3200,
        ttftMs: 840,
        totalMs: 11300,
        tokensInput: 1900,
        tokensOutput: 1300,
        costUsd: 0.016,
      },
    ],
    finalResult: {
      taskId: "TSK-D4k",
      summary: "Baron-Kenny mediation and counterfactual frameworks are the two dominant SEM approaches in epidemiology, with counterfactual methods gaining preference for handling confounding.",
      evidence: [
        { referenceId: 1, claim: "Baron-Kenny remains widely used despite limitations with binary outcomes", strength: "strong" },
        { referenceId: 3, claim: "Counterfactual mediation allows decomposition of natural direct and indirect effects", strength: "strong" },
      ],
      confidence: 0.82,
      reasoningChain: [
        "Searched for SEM mediation approaches in epidemiology",
        "Identified Baron-Kenny and counterfactual as dominant paradigms",
        "Compared limitations: Baron-Kenny struggles with confounders",
      ],
      citedReferenceIds: [1, 3],
    },
  },
];
